iMedical/config/routes.rb
Rails.application.routes.draw do

	get 'auth/:provider/callback', to: 'sessions#createOauth'
	get 'auth/failure', to: redirect('/')

	# Role chosing
	get 'users/:id/newOwner' => 'users#newOwner', as: :new_owner
	get 'users/:id/newDoctor' => 'users#newDoctor', as: :new_doctor
	get 'users/:id/newPatient' => 'users#newPatient', as: :new_patient
	get 'users/:id/newSecretary' => 'users#newSecretary', as: :new_secretary
	get 'users/:id/newOauth' => 'users#newOauth', as: :newOauth


	# Checking/setting doctorID
	get 'users/:id/setDoctorID' => 'users#setDoctorID', as: :set_doctorid
	patch 'users/:id/setDoctorID' => 'users#patchDoctorID', as: :patch_doctorid

	# Owner's routes
	get '/owner/:owner_id/clinics/showClinicsForDoctor' => 'clinics#showClinicsForDoctor', as: :show_clinicsDoctor
	get '/owner/:owner_id/clinics/showClinicsForSecretary' => 'clinics#showClinicsForSecretary', as: :show_clinicsSecretary
	get '/owner/:owner_id/clinics/:id/searchDoctor' => 'clinics#searchDoctor', as: :search_doctor
	get '/owner/:owner_id/clinics/:id/searchSecretary' => 'clinics#searchSecretary', as: :search_secretary
	get '/work/addNewDoctor/:doctor_id&:clinic_id' => 'works#addNewDoctor', as: :add_new_doctor
	get '/manage/addNewSecretary/:secretary_id&:clinic_id' => 'manages#addNewSecretary', as: :add_new_secretary

	#Secretary's routes
	get '/secretary/:secretary_id/clinics/showClinics' => 'clinics#showClinics', as: :show_clinics
    get '/secretary/:secretary_id/clinics/:clinic_id/doctors/:doctor_id/searchPatient' => 'users#searchPatient', as: :search_patient

	# Patient's routes
	get '/patient/:id/showStory' => 'users#showPatientStory', as: :show_patient_story
	get '/patient/searchClinic' => 'users#searchClinic', as: :search_clinic
	get '/patient/clinics/:clinic_id/showDoctors/:doctor_id/createExamination' => 'examinations#createExamination', as: :create_examination

	# Clinics

	get '/clinics/:id' => 'clinics#show', as: :clinics_show
	#get 'examinations/calendar', as: :examinations_calendar

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#createLocal'
	delete '/logout' => 'sessions#destroy', as: :logout

	resources :sessions, only: [:create, :destroy, :new]
	resources :home, only: [:show]
	resources :users, only: [:show, :new, :create, :destroy, :update, :edit, :index ]
	#resources :doctors, controller: 'users', type: 'Doctor' do
	#	resources :clinics, shallow: true do
	#		resources :patient, controller: 'users', type: 'Patient', shallow: true do
	#			resources :examinations, shallow: true do
	#				resources :prescriptions
	#			end
	#		end
	#	end
	#end

	# I want to see where the given doctor works
	resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show] do
		resources :clinics, shallow: true, only: [:index, :show]
	end
	# I want to see the patient that had a visit in the given clinic
	resources :clinics, only: [:index, :show] do
		resources :patients, controller: 'users', type: 'Patient', only: [:index, :show] do
			resources :examinations, only: [:index]
		end
		#resources :doctors, controller: 'user', type: 'Doctor', shallow: true
		resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show] do
			resources :examinations, only: [:create, :index]
		end
	end
	# I want to see the visits of a patient
	resources :patients, controller: 'users', type: 'Patient', only: [:index, :show] do
		resources :examinations, shallow: true, only: [:index, :show, :create]
		#resources :prescriptions, shallow: true
	end
	# I want to see the prescriptions of a examinations
	resources :examinations do
		resources :prescriptions, shallow: true
		resources :drugs, controller: 'prescriptions', type: 'Drug', only: [:new, :create]
		resources :prescriptedExaminations, controller: 'prescriptions', type: 'PrescriptedExamination', only: [:new, :create]
	end

	# Route to search drug
	get '/searchDrug', to: 'prescriptions#searchDrug', as:  :search_drug

	resources :secretaries, controller: 'users', type: 'Secretary', only: [:index, :show] do
		resources :clinics, shallow: true, only: [:index, :show]
	end

	#resources :patient, controller: 'users', type: 'Patient'
	resources :manages, only: [:new, :destroy] do
		#resources :clinics
		#resources :secretaries
	end

	resources :owner, controller: 'users', type: 'Owner', only: [:show] do
		resources :clinics do
			resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show]
			resources :secretaries, controller: 'users', type: 'Secretary', only: [:index]
		end
	end
	resources :works, only: [:new, :create, :destroy] do
		#resources :clinics
		#resources :doctors
	end
	resources :homepage, only: [:index]
	resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]

	root "homepage#index"

end

iMedical/app/models/clinic.rb
class Clinic < ApplicationRecord

    belongs_to :owner
    has_many :works
    has_many :examinations
    has_many :manages
    has_many :secretaries, through: :manages


    geocoded_by :address

    def self.search(search_term)
        where("LOWER(name) LIKE ?", "%#{search_term.downcase}%")
    end

end

iMedical/app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
	load_and_authorize_resource
	
    def index
        if(session[:type] == "Owner")
            @owner = User.get_owners.find(params[:owner_id])
            #@clinics = @owner.clinics
            @clinics = Clinic.where("owner_id = ?", @owner.id)
        else
            @secretary = User.get_secretaries.find(params[:secretary_id])
            #@clinics = @secretary.clinics
            @clinics = Clinic.joins("INNER JOIN manages ON clinics.id = manages.clinic_id").where("manages.secretary_id = ?", @secretary.id)
        end

    end

    def show
		# If the user is a patient I show the doctors that work in this clinic
        if(session[:type] == "Patient")
            @clinic = Clinic.find(params[:id])
        end
		# If the user is a secretary I show the doctors that work in this clinic
		# If the user is a owner I show.. nothing?
		#puts session
		#puts params
		clinic = Clinic.find(params[:id])
		case session[:type]
			when "Doctor"
				# If the user is a doctor I show his patients
				# The doctor id is stored in session[:user_id]
				redirect_to clinic_patients_path(clinic)
			when "Secretary"

			when "Patient"

			when "Owner"
				@owner = User.get_owners.find(params[:owner_id])
				#@clinics = @owner.clinics
				@clinics = Clinic.where("owner_id = ?", @owner.id)
		end
    end

    def calendar
        if(session[:type])
            @clinic = Clinic.find(params[:id])
        end
    end

    def new
        @clinic = Clinic.new
    end

    def create
        #@owner = User.get_owners.find(params[:owner_id])
        @owner = User.get_owners.find(session[:user_id])
        #@clinic = @owner.clinics.create!(clinic_params)
        @clinic = Clinic.create!(clinic_params)
        @clinic.owner_id = current_user.id
        @clinic.save
        #redirect_to new_owner_path(params[:owner_id])
        redirect_to new_owner_path(session[:user_id])
    end

    def edit
        @owner = User.get_owners.find(params[:owner_id])
        @clinic = Clinic.find(params[:id])
    end

    def update
        @owner = User.get_owners.find(params[:owner_id])
        @clinic = Clinic.find(params[:id])
        @clinic.update(clinic_params)
        redirect_to new_owner_path(params[:owner_id])
    end

    def showClinics
        @secretary = User.get_secretaries.find(params[:secretary_id])
        #@clinics = @secretary.clinics
		@clinics = Clinic.joins("INNER JOIN manages ON clinics.id = manages.clinic_id").where("manages.secretary_id = ?", @secretary.id)
    end
    
    # Owner's functions

    def showClinicsForDoctor
        @owner = User.get_owners.find(params[:owner_id])
        #@clinics = @owner.clinics
        @clinics = Clinic.where("owner_id = ?", @owner.id)
    end

    def showClinicsForSecretary
        @owner = User.get_owners.find(params[:owner_id])
        #@clinics = @owner.clinics
        @clinics = Clinic.where("owner_id = ?", @owner.id)
    end

    def searchDoctor
        if(session[:type] == "Owner")
            session[:clinic_id] = Clinic.find(params[:id])
		    @doctors = User.get_doctors.all.order('created_at DESC')
		    @works = Work.where("clinic_id = ?", params[:id])
		    @doctors = @doctors.search(params[:search]) if params[:search].present?
			@works = Work.select("DISTINCT doctor_id").where("works.clinic_id = ?", params[:id])
			@wd = []
			i = 0
			while i < @works.length
				@wd.push(@works[i].doctor_id)
				i = i + 1
			end
			#puts @wd
        elsif(session[:type] == "Secretary")
            #session[:clinic_id] = Clinic.find(params[:id])
			@doctors = User.get_doctors.joins("INNER JOIN works ON users.id = works.doctor_id").where("works.clinic_id = ?", params[:id]).order('created_at DESC').uniq
		    @doctors = @doctors.search(params[:search]) if params[:search].present?
        end
	end

	def searchSecretary
        session[:clinic_id] = Clinic.find(params[:id])
		@secretaries = User.get_secretaries.all.order('created_at DESC')
		@secretaries = @secretaries.search(params[:search]) if params[:search].present?
		@manages = Manage.select("DISTINCT secretary_id").where("manages.clinic_id = ?", params[:id])
		@workingSecretaries = []
		i = 0
		while i < @manages.length
			@workingSecretaries.push(@manages[i].secretary_id)
			i = i + 1
		end
	end

    private

    def clinic_params
        params.require(:clinic).permit(:name, :address, :description, :province, :city, :latitude, :longitude).merge(owner_id: current_user.id)
    end

	# Method to verify if the user with the actual role can go in this page
	def verifyRole
		# The role is set in session variable :role
	end
end

iMedical/app/helpers/clinics_helper.rb
module ClinicsHelper
end

iMedical/app/views/clinics/addNewSecretary.html.erb
<%= form_tag(add_new_doctor_path, method: :get, id: "owDoct-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search ..." %>
<% end %>
<table>
    <% @secretaries.each do |secretary| %>
        <tr>
            <td><%= secretary.name %></td>
        </tr>
    <% end %>
</table>

iMedical/app/views/clinics/edit.html.erb
<h1>MODIFICA STUDIO MEDICO</h1>

<%= form_for [@owner, @clinic], :url => owner_clinic_path do |f| %>
    <div>
        <%= f.label :nome%>
        <%= f.text_field :name%>
    </div>
    <div>
		<%= f.label :indirizzo%>
		<%= f.text_field :address%>
	</div>
    <div>
		<%= f.label :descrizione%>
		<%= f.text_area :description%>
	</div>
	<div>
        <%= f.submit "Modifica" %>
    </div>
<% end %>

iMedical/app/views/clinics/index.html.erb
<h1>GESTISCI STUDI MEDICI</h1>
<h2>Ci sono <%= @clinics.count %> studi medici creati da te</h2>

<table>
    <thead>
        <tr>
            <th>Nome Studio</th>
        </tr>
    </thead>

    <tbody>
        <% @clinics.each do |clinic| %>
        <tr>
            <td><%= clinic.name %>
                <%= button_to "Modifica studio medico", edit_owner_clinic_path(current_user.id, clinic.id), :method => :get, class: "btn" %>
            </td>
            <td>
				<%= button_to "Gestisci medici dello studio", owner_clinic_doctors_path(current_user.id, clinic.id), :method => :get, class: "btn" %>
            </td>
			<td>
				<%= button_to "Gestisci segretari dello studio", owner_clinic_secretaries_path(current_user.id, clinic.id), :method => :get, class: "btn" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

iMedical/app/views/clinics/new.html.erb
<% provide(:title, 'Nuovo studio medico') %>
<h1> Crea nuovo studio medico </h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @clinic, :url => {:controller => "clinics", :action => "create"} do |f| %>
			<div>
				<%= f.label :nome%>
				<%= f.text_field :name, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :indirizzo%>
				<%= f.text_field :address, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :città%>
				<%= f.text_field :city, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :provincia%>
				<%= f.text_field :province, class: 'form-control' %>
			</div>

		    <div>
				<%= f.label :descrizione%>
				<%= f.text_area :description, class: 'form-control' %>
			</div>

			<div>
				<%= f.submit "Crea nuovo studio", class: "btn btn-primary" %>
			</div>

		<% end %>
	</div>
</div>	

iMedical/app/views/clinics/searchDoctor.html.erb
<%= form_tag(search_doctor_path, method: :get, id: "searchDoct-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search ..." %>
<% end %>
<table>
    <% @doctors.each do |doctor| %>
        <tr>
            <% if(session[:type] == "Owner") %>
                <td><%= doctor.name %>
					<% if !@wd.include?(doctor.id) %>
						<%= button_to "Aggiungi Medico", add_new_doctor_path(doctor.id, session[:clinic_id]), :method => :get, class: "btn" %>
					<% end %>
				</td>
            <% elsif(session[:type] == "Patient") %>
                <td><%= doctor.name %><%= button_to "Prenota visita", add_new_doctor_path(doctor.id, session[:clinic_id]), :method => :get, class: "btn" %></td>
            <% elsif(session[:type] == "Secretary") %>
                <td><%= doctor.name %> <%= button_to "Visualizza Visite",  clinic_doctor_path(params[:id], doctor.id), :method => :get, class: "btn" %></td>  
            <% end %>
        </tr>
    <% end %>
</table>

iMedical/app/views/clinics/searchPatient.html.erb
<%= form_tag(search_secretary_path, method: :get, id: "owDoct-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search ..." %>
<% end %>
<table>
    <% @patients.each do |patient| %>
        <tr>
            <td><%= patient.name %>
				<% if !@workingPatients.include?(patient.id) %>
					<%= button_to "Prenota", clinic_doctor_path(params[:id], doctor.id), :method => :get, class: "btn" %>
				<% end %>
			</td>
        </tr>
    <% end %>
</table>

iMedical/app/views/clinics/searchSecretary.html.erb
<%= form_tag(search_secretary_path, method: :get, id: "owDoct-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search ..." %>
<% end %>
<table>
    <% @secretaries.each do |secretary| %>
        <tr>
            <td><%= secretary.name %>
				<% if !@workingSecretaries.include?(secretary.id) %>
					<%= button_to "Aggiungi Segretario", add_new_secretary_path(secretary.id, session[:clinic_id]), :method => :get, class: "btn" %>
				<% end %>
			</td>
        </tr>
    <% end %>
</table>

iMedical/app/views/clinics/show.html.erb
<h1 class="display-4"> INFORMAZIONI CLINICA </h1>

<h2>Indirizzo: <%= @clinic.address + " " + @clinic.city + ", " + @clinic.province %></h2>
<h2>Coordinate: <%= @clinic.latitude %> <%= @clinic.longitude %></h2>
<%= link_to "Lista medici", clinic_doctors_path(@clinic) %> <br>

<iframe
    width="900"
    height="650"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=<%=Rails.application.credentials.google[:API_KEY]%>&q=Italy, <%= @clinic.address + " " + @clinic.city + ", " + @clinic.province %>" allowfullscreen>
</iframe>

iMedical/app/views/clinics/showClinics.html.erb
<h1>RICERCA STUDI MEDICI</h1>

<table>
    <thead>
        <tr>
            <th>Nome Studio</th>
        </tr>
    </thead>

    <tbody>
        <% @clinics.each do |clinic| %>
        <tr>
            <td>
                <%= clinic.name %><%= button_to "Cerca Medico", search_doctor_path(current_user.id, clinic.id), :method => :get, class: "btn" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

iMedical/app/views/clinics/showClinicsForDoctor.html.erb
<h1>GESTISCI STUDI MEDICI</h1>
<h2>Ci sono <%= @clinics.count %> studi medici creati da te</h2>

<table>
    <thead>
        <tr>
            <th>Nome Studio</th>
        </tr>
    </thead>

    <tbody>
        <% @clinics.each do |clinic| %>
        <tr>
            <td>
                <%= clinic.name %><%= button_to "Cerca medico", search_doctor_path(current_user.id, clinic.id), :method => :get, class: "btn" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

iMedical/app/views/clinics/showClinicsForSecretary.html.erb
<h1>GESTISCI STUDI MEDICI</h1>
<h2>Ci sono <%= @clinics.count %> studi medici creati da te</h2>

<table>
    <thead>
        <tr>
            <th>Nome Studio</th>
        </tr>
    </thead>

    <tbody>
        <% @clinics.each do |clinic| %>
        <tr>
            <td>
                <%= clinic.name %><%= button_to "Cerca segretario", search_secretary_path(current_user.id, clinic.id), :method => :get, class: "btn" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>