iMedical/config/routes.rb
Rails.application.routes.draw do

	get 'auth/:provider/callback', to: 'sessions#createOauth'
	get 'auth/failure', to: redirect('/')

	# Role chosing
	get 'users/:id/newOwner' => 'users#newOwner', as: :new_owner
	get 'users/:id/newDoctor' => 'users#newDoctor', as: :new_doctor
	get 'users/:id/newPatient' => 'users#newPatient', as: :new_patient
	get 'users/:id/newSecretary' => 'users#newSecretary', as: :new_secretary
	get 'users/:id/newOauth' => 'users#newOauth', as: :newOauth


	# Checking/setting doctorID
	get 'users/:id/setDoctorID' => 'users#setDoctorID', as: :set_doctorid
	patch 'users/:id/setDoctorID' => 'users#patchDoctorID', as: :patch_doctorid

	# Owner's routes
	get '/owner/:owner_id/clinics/showClinicsForDoctor' => 'clinics#showClinicsForDoctor', as: :show_clinicsDoctor
	get '/owner/:owner_id/clinics/showClinicsForSecretary' => 'clinics#showClinicsForSecretary', as: :show_clinicsSecretary
	get '/owner/:owner_id/clinics/:id/searchDoctor' => 'clinics#searchDoctor', as: :search_doctor
	get '/owner/:owner_id/clinics/:id/searchSecretary' => 'clinics#searchSecretary', as: :search_secretary
	get '/work/addNewDoctor/:doctor_id&:clinic_id' => 'works#addNewDoctor', as: :add_new_doctor
	get '/manage/addNewSecretary/:secretary_id&:clinic_id' => 'manages#addNewSecretary', as: :add_new_secretary

	#Secretary's routes
	get '/secretary/:secretary_id/clinics/showClinics' => 'clinics#showClinics', as: :show_clinics
    get '/secretary/:secretary_id/clinics/:clinic_id/doctors/:doctor_id/searchPatient' => 'users#searchPatient', as: :search_patient

	# Patient's routes
	get '/patient/:id/showStory' => 'users#showPatientStory', as: :show_patient_story
	get '/patient/searchClinic' => 'users#searchClinic', as: :search_clinic
	get '/patient/clinics/:clinic_id/showDoctors/:doctor_id/createExamination' => 'examinations#createExamination', as: :create_examination

	# Clinics

	get '/clinics/:id' => 'clinics#show', as: :clinics_show
	#get 'examinations/calendar', as: :examinations_calendar

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#createLocal'
	delete '/logout' => 'sessions#destroy', as: :logout

	resources :sessions, only: [:create, :destroy, :new]
	resources :home, only: [:show]
	resources :users, only: [:show, :new, :create, :destroy, :update, :edit, :index ]
	#resources :doctors, controller: 'users', type: 'Doctor' do
	#	resources :clinics, shallow: true do
	#		resources :patient, controller: 'users', type: 'Patient', shallow: true do
	#			resources :examinations, shallow: true do
	#				resources :prescriptions
	#			end
	#		end
	#	end
	#end

	# I want to see where the given doctor works
	resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show] do
		resources :clinics, shallow: true, only: [:index, :show]
	end
	# I want to see the patient that had a visit in the given clinic
	resources :clinics, only: [:index, :show] do
		resources :patients, controller: 'users', type: 'Patient', only: [:index, :show] do
			resources :examinations, only: [:index]
		end
		#resources :doctors, controller: 'user', type: 'Doctor', shallow: true
		resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show] do
			resources :examinations, only: [:create, :index]
		end
	end
	# I want to see the visits of a patient
	resources :patients, controller: 'users', type: 'Patient', only: [:index, :show] do
		resources :examinations, shallow: true, only: [:index, :show, :create]
		#resources :prescriptions, shallow: true
	end
	# I want to see the prescriptions of a examinations
	resources :examinations do
		resources :prescriptions, shallow: true
		resources :drugs, controller: 'prescriptions', type: 'Drug', only: [:new, :create]
		resources :prescriptedExaminations, controller: 'prescriptions', type: 'PrescriptedExamination', only: [:new, :create]
	end

	# Route to search drug
	get '/searchDrug', to: 'prescriptions#searchDrug', as:  :search_drug

	resources :secretaries, controller: 'users', type: 'Secretary', only: [:index, :show] do
		resources :clinics, shallow: true, only: [:index, :show]
	end

	#resources :patient, controller: 'users', type: 'Patient'
	resources :manages, only: [:new, :destroy] do
		#resources :clinics
		#resources :secretaries
	end

	resources :owner, controller: 'users', type: 'Owner', only: [:show] do
		resources :clinics do
			resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show]
			resources :secretaries, controller: 'users', type: 'Secretary', only: [:index]
		end
	end
	resources :works, only: [:new, :create, :destroy] do
		#resources :clinics
		#resources :doctors
	end
	resources :homepage, only: [:index]
	resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]

	root "homepage#index"

end

iMedical/app/models/prescription.rb
class Prescription < ApplicationRecord

    belongs_to :examination

end

iMedical/app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController	
	load_and_authorize_resource	
	skip_authorize_resource :only => [:create, :new]
	def index
		case session[:type]
			when "Doctor"
				# List of prescriptions of the selected examination
				@examination = Examination.find(params[:examination_id])
				@prescriptions = @examination.prescriptions
				render "doctorPrescriptionsIndex"
			when "Secretary"
				#@examination = Examination.find(params[:examination_id])
				#@prescriptions = @examination.prescriptions	
			when "Patient"
				#@patient = Patient.find(params[:patient_id])
				@examination = Examination.find(params[:examination_id])
				@prescriptions = @examination.prescriptions
				render "patientPrescriptionsIndex"
			when "Owner"	
		end
	end
	
	def show
		@prescription = Prescription.find(params[:id])
		case session[:type]
			when "Doctor"
				case @prescription.type
					when "Drug"
						render "doctorDrugShow"
					when "PrescriptedExamination"
						render "doctorPrescriptedExaminationShow"
				end
			when "Secretary"
			
			when "Patient"
				case @prescription.type
					when "Drug"
						render "doctorDrugShow"
					when "PrescriptedExamination"
						render "doctorPrescriptedExaminationShow"
				end
			when "Owner"	
		end
	end
	
	def new
		case session[:type]
			when "Doctor"
				case params[:type]
					when "Drug"
						@examination = Examination.find(params[:examination_id])
						@prescription = @examination.prescriptions.new
						@prescription.type = "PrescriptedExamination"
						render "doctorDrugPrescriptionNew"
					when "PrescriptedExamination"
						@examination = Examination.find(params[:examination_id])
						@prescription = @examination.prescriptions.new
						@prescription.type = "PrescriptedExamination"
						render "doctorPrescriptionsNew"
				end
			when "Secretary"
				#Nothing
			when "Patient"
				#Nothing
			when "Owner"	
				#Nothing
		end
	end

	def create
		params.require(:type)
		prescription = Prescription.new
		case session[:type]
			when "Doctor"
				params.require(:examination_id)
				@examination = Examination.find(params[:examination_id])
				case params[:type]
					when "Drug"
						params.require(:prescription).permit(:comment, :drugName)
						prescription.comment = params[:prescription][:comment]
						prescription.drugName = params[:prescription][:drugName]
						prescription.type = params[:type]
						prescription.examination_id = params[:examination_id]	
					when "PrescriptedExamination"
						params.require(:prescription).permit(:comment)
						prescription.comment = params[:prescription][:comment]
						prescription.type = params[:type]
						prescription.examination_id = params[:examination_id]
				end
				authorize! :create, prescription
				prescription.save
				redirect_to examination_prescriptions_path(@examination)
			when "Secretary"
			
			when "Patient"
				redirect_to patient_prescriptions_path(current_user.id)
			when "Owner"
		end
	end
	
	def edit
		@prescription = Prescription.find(params[:id])
		case @prescription.type
			when "Drug"
				render "doctorDrugEdit"
			when "PrescriptedExamination"
				render "doctorPrescriptedExaminationEdit"
		end
	end
	
	def update
		prescription = Prescription.find(params[:id])
		examination = Examination.find(prescription.examination_id)
		case prescription.type
			when "Drug"
				prescription.drugName = params[:drug][:drugName]
				prescription.comment = params[:drug][:comment]
			when "PrescriptedExamination"
				prescription.comment = params[:prescripted_examination][:comment]
		end
		prescription.save
		redirect_to examination_prescriptions_path(examination)
	end
	
	def destroy
		prescription = Prescription.find(params[:id])
		examination = Examination.find(prescription.examination_id)
		Prescription.delete(params[:id])
		redirect_to examination_prescriptions_path(examination)
	end
	
	def searchDrug
		if params[:name].length > 3
			render :json => Drug.search(params[:name])
		end
	end

  #def type:String
  #end

  #def comment:String
  #end

  #def medicinalName:String
  #end
   # def create
     #   if(session[:type] == "Doctor")
      #      @examination = Examination.find(params[:examination_id])
      #      @prescription = @examination.prescriptions.create!(prescription_params)
      #      @prescription.examination_id = @examination.id
      #      @prescription.save
      #      redirect_to new_doctor_path(current_user.id)
      #  else
      #      redirect_to patient_prescriptions_path(current_user.id)
     #   end
   #  end

    private

    def prescription_params
        params.require(:prescription).permit(:type, :comment, :drugName)
    end


end

iMedical/app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

iMedical/app/views/prescriptions/doctorDrugEdit.html.erb
<h2> Modifica prescrizione farmaco </h2>
<%= form_for @prescription, url: prescription_path do |p| %>
	<div>
		<%= p.label :drugName%>
		<%= p.text_field :drugName %>
	</div>
	
	<div>
		<%= p.label :comment%>
		<%= p.text_field :comment %>
	</div>
	
	<div>
		<%= p.submit "Modifica prescrizione" %>
	</div>

<% end %>

iMedical/app/views/prescriptions/doctorDrugPrescriptionNew.html.erb
<h2> Creazione prescrizione di un farmaco per determinata visita (Vista Dottore) </h2>

<%= form_for @prescription, url: examination_drugs_path do |p| %>
	<div>
		<%= p.label :farmaco%>
		<%= p.text_field :drugName, autofocus: true %>
	</div>

	<div>
		<%= p.label :dosaggio%>
		<%= p.text_field :comment, autofocus: true %>
	</div>

	<div>
		<%= p.submit "Inserisci prescrizione" %>
	</div>

<% end %>
<br>
<h2> Farmaci trovati </h2> <br>
<div id='farmaci'>
	
</div>

iMedical/app/views/prescriptions/doctorDrugShow.html.erb
<h2> Farmaco prescritto </h2>
<br>
<b> Farmaco: </b> <%= @prescription.drugName %> <br>
<b> Dosaggio: </b> <%= @prescription.comment %> <br>
<br>
<% if (session[:type] == "Doctor") %>
	<%= button_to "Modifica prescrizione farmaco", edit_prescription_path(@prescription), method: :get %> <br>
<% end %>
<% if (session[:type] == "Doctor") %>	
	<%= button_to "Elimina prescrizione farmaco", prescription_path(@prescription), method: :delete %>
<% end %>

iMedical/app/views/prescriptions/doctorPrescriptedExaminationEdit.html.erb
<h2> Modifica prescrizione visita </h2>
<%= form_for @prescription, url: prescription_path do |p| %>
	<div>
		<%= p.label :comment%>
		<%= p.text_field :comment %>
	</div>

	<div>
		<%= p.submit "Modifica prescrizione" %>
	</div>

<% end %>

iMedical/app/views/prescriptions/doctorPrescriptedExaminationShow.html.erb
<h2> Visita prescritta </h2>
<br>
<b> Commento: </b> <%= @prescription.comment %> <br>
<br>
<% if (session[:type] == "Doctor") %>
	<%= button_to "Modifica prescrizione visita", edit_prescription_path(@prescription), method: :get %> <br>
<% end %>
<% if (session[:type] == "Doctor") %>
	<%= button_to "Elimina prescrizione farmaco", prescription_path(@prescription), method: :delete %>
<% end %>

iMedical/app/views/prescriptions/doctorPrescriptionsIndex.html.erb
<h2> Prescrizioni di una data visita (vista del medico) </h2>
<br>

<table border="1">
	<% @prescriptions.each do |prescription| %>
		<tr> 
			<td> <%= prescription.id %> </td> 
			<td> <%= prescription.type %> </td>
			<td> <%= button_to "Visualizza prescrizione", prescription_path(prescription), method: :get %>  </td>
		</tr> 
	<% end %>
</table>

iMedical/app/views/prescriptions/doctorPrescriptionsNew.html.erb
<h2> Creazione prescrizione di una visita per determinata visita (Vista Dottore) </h2>

<%= form_for @prescription, url: examination_prescriptedExaminations_path do |p| %>
	
	<div>
		<%= p.label :comment%>
		<%= p.text_field :comment, autofocus: true %>
	</div>

	<div>
		<%= p.submit "Inserisci prescrizione" %>
	</div>

<% end %>

iMedical/app/views/prescriptions/index.html.erb
<h1>PRESCRIZIONI</h1>


<!-- ARRIVO QUA CON examination_prescriptions_path -->

<table>
    <thead>
        <tr>
            <th>Prescrizione</th>
        </tr>
    </thead>
    <tbody>
        <% @prescriptions.each do |prescription| %>
        <tr>
            <td><%= prescription.name %></td>
        </tr>
        <% end %>
    </tbody>
</table>

iMedical/app/views/prescriptions/patientPrescriptionsIndex.html.erb
<h2> Prescrizioni di una data visita (vista del paziente) </h2>
<br>
<table>
	<% @prescriptions.each do |prescription| %>
		<tr> <td> <%= button_to prescription.id, prescription_path(prescription), method: :get %>  </td> </tr> 
	<% end %>
</table>