iMedical/config/routes.rb
Rails.application.routes.draw do

	get 'auth/:provider/callback', to: 'sessions#createOauth'
	get 'auth/failure', to: redirect('/')

	# Role chosing
	get 'users/:id/newOwner' => 'users#newOwner', as: :new_owner
	get 'users/:id/newDoctor' => 'users#newDoctor', as: :new_doctor
	get 'users/:id/newPatient' => 'users#newPatient', as: :new_patient
	get 'users/:id/newSecretary' => 'users#newSecretary', as: :new_secretary
	get 'users/:id/newOauth' => 'users#newOauth', as: :newOauth


	# Checking/setting doctorID
	get 'users/:id/setDoctorID' => 'users#setDoctorID', as: :set_doctorid
	patch 'users/:id/setDoctorID' => 'users#patchDoctorID', as: :patch_doctorid

	# Owner's routes
	get '/owner/:owner_id/clinics/showClinicsForDoctor' => 'clinics#showClinicsForDoctor', as: :show_clinicsDoctor
	get '/owner/:owner_id/clinics/showClinicsForSecretary' => 'clinics#showClinicsForSecretary', as: :show_clinicsSecretary
	get '/owner/:owner_id/clinics/:id/searchDoctor' => 'clinics#searchDoctor', as: :search_doctor
	get '/owner/:owner_id/clinics/:id/searchSecretary' => 'clinics#searchSecretary', as: :search_secretary
	get '/work/addNewDoctor/:doctor_id&:clinic_id' => 'works#addNewDoctor', as: :add_new_doctor
	get '/manage/addNewSecretary/:secretary_id&:clinic_id' => 'manages#addNewSecretary', as: :add_new_secretary

	#Secretary's routes
	get '/secretary/:secretary_id/clinics/showClinics' => 'clinics#showClinics', as: :show_clinics
    get '/secretary/:secretary_id/clinics/:clinic_id/doctors/:doctor_id/searchPatient' => 'users#searchPatient', as: :search_patient

	# Patient's routes
	get '/patient/:id/showStory' => 'users#showPatientStory', as: :show_patient_story
	get '/patient/searchClinic' => 'users#searchClinic', as: :search_clinic
	get '/patient/clinics/:clinic_id/showDoctors/:doctor_id/createExamination' => 'examinations#createExamination', as: :create_examination

	# Clinics

	get '/clinics/:id' => 'clinics#show', as: :clinics_show
	#get 'examinations/calendar', as: :examinations_calendar

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#createLocal'
	delete '/logout' => 'sessions#destroy', as: :logout

	resources :sessions, only: [:create, :destroy, :new]
	resources :home, only: [:show]
	resources :users, only: [:show, :new, :create, :destroy, :update, :edit, :index ]
	#resources :doctors, controller: 'users', type: 'Doctor' do
	#	resources :clinics, shallow: true do
	#		resources :patient, controller: 'users', type: 'Patient', shallow: true do
	#			resources :examinations, shallow: true do
	#				resources :prescriptions
	#			end
	#		end
	#	end
	#end

	# I want to see where the given doctor works
	resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show] do
		resources :clinics, shallow: true, only: [:index, :show]
	end
	# I want to see the patient that had a visit in the given clinic
	resources :clinics, only: [:index, :show] do
		resources :patients, controller: 'users', type: 'Patient', only: [:index, :show] do
			resources :examinations, only: [:index]
		end
		#resources :doctors, controller: 'user', type: 'Doctor', shallow: true
		resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show] do
			resources :examinations, only: [:create, :index]
		end
	end
	# I want to see the visits of a patient
	resources :patients, controller: 'users', type: 'Patient', only: [:index, :show] do
		resources :examinations, shallow: true, only: [:index, :show, :create]
		#resources :prescriptions, shallow: true
	end
	# I want to see the prescriptions of a examinations
	resources :examinations do
		resources :prescriptions, shallow: true
		resources :drugs, controller: 'prescriptions', type: 'Drug', only: [:new, :create]
		resources :prescriptedExaminations, controller: 'prescriptions', type: 'PrescriptedExamination', only: [:new, :create]
	end

	# Route to search drug
	get '/searchDrug', to: 'prescriptions#searchDrug', as:  :search_drug

	resources :secretaries, controller: 'users', type: 'Secretary', only: [:index, :show] do
		resources :clinics, shallow: true, only: [:index, :show]
	end

	#resources :patient, controller: 'users', type: 'Patient'
	resources :manages, only: [:new, :destroy] do
		#resources :clinics
		#resources :secretaries
	end

	resources :owner, controller: 'users', type: 'Owner', only: [:show] do
		resources :clinics do
			resources :doctors, controller: 'users', type: 'Doctor', only: [:index, :show]
			resources :secretaries, controller: 'users', type: 'Secretary', only: [:index]
		end
	end
	resources :works, only: [:new, :create, :destroy] do
		#resources :clinics
		#resources :doctors
	end
	resources :homepage, only: [:index]
	resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]

	root "homepage#index"

end

iMedical/app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	def new
		@user = User.new
	end

	def index
		# Different view for every role
		#puts params
		#puts session[:role]
		case session[:type]
			when "Doctor"
				case params[:type]
					when "Doctor"

					when "Secretary"

					when "Owner"

					when "Patient"
						# List of patients if the user has connected as Doctor
						# The doctor id is stored in session[:user_id]
						@patients = User.get_patients.joins("INNER JOIN examinations ON users.id = examinations.patient_id").where("examinations.doctor_id = ? AND examinations.clinic_id = ?", session[:user_id], params[:clinic_id]).uniq
						#puts params
						@clinic = Clinic.find(params[:clinic_id])
						render "doctorPatients"
				end
			when "Secretary"

			when "Owner"
				case params[:type]
					when "Doctor"
						params.require(:clinic_id)
						@doctors = User.get_doctors.joins("INNER JOIN works ON users.id = works.doctor_id").where("works.clinic_id = ?", params[:clinic_id]).uniq
						@clinic = Clinic.find(params[:clinic_id])
						render "ownerClinicDoctorsIndex"
					when "Secretary"
						params.require(:clinic_id)
						@secretaries = User.get_secretaries.select("manages.id, users.name, users.surname").joins("INNER JOIN manages ON users.id = manages.secretary_id").where("manages.clinic_id = ?", params[:clinic_id])
						render "ownerClinicSecretariesIndex"
				end
			when "Patient"
				# Dove devo metterle?
				@users= User.all.order('created_at DESC')
				@users = @users.search(params[:search]) if params[:search].present?
				case params[:type]
					when "Doctor"
						@clinic = Clinic.find(params[:clinic_id])
						@doctors = User.get_doctors.joins("INNER JOIN works ON users.id = works.doctor_id").where("works.clinic_id = ?", params[:clinic_id]).uniq
						render "patientClinicDoctorsShow"
				end
		end
	end

	def show
		#puts params
		# Role of the session
		case session[:type]
			when "Doctor"
				case params[:type]
					when "Doctor"
						# La vista dovrebbe variare in base a ciò che è l'utente, memorizzare nella sessione che cosa è l'utente?
						# Ovvero quando clicca quale tipo di utenza è, memorizzarla nella sessione
						# Select all clinics where the doctor works ( i'm a doctor ancora non controllato )
						#@clinics = Clinic.joins("INNER JOIN works ON works.clinic_id = clinics.id").where("works.doctor_id = ?", session[:user_id])
						@clinics = Clinic.joins("INNER JOIN works ON works.clinic_id = clinics.id").where("works.doctor_id = ?", session[:user_id]).uniq
						#puts @clinics.all
						#puts session[:user_id]
						render 'showDoctor'
					when "Secretary"

					when "Owner"

					when "Patient"
						# See the menu where i can choose my examination of the patient on the selected clinic
						patient = User.get_patients.find(params[:id])
						clinic = Clinic.find(params[:clinic_id])
						redirect_to clinic_patient_examinations_path(clinic, patient)
				end

			when "Secretary"
				puts params
				case params[:type]
					when "Doctor"
						if params[:date] == nil
							redirect_to clinic_doctor_path(params[:clinic_id], params[:id])+"?date="+DateTime.now.to_date.to_s
						else
							@clinic = Clinic.find(params[:clinic_id])
							@doctor = User.get_doctors.find(params[:id])
							@examinations = getExaminations()
							@nextDay = (params[:date].to_date + 1.days).to_s
							@previousDay = (params[:date].to_date - 1.days).to_s
							@works = Work.select('day, start_time, end_time').where("clinic_id = ? AND doctor_id = ? AND day = ?", params[:clinic_id], params[:id], params[:date].to_date.wday)
							@bookableDates = []
							if @works.length != 0
								@startDateTime = params[:date] + " " + @works[0].start_time
								@endDateTime = params[:date] + " " + @works[0].end_time
								@bookableDates = getBookableDates(@examinations, @startDateTime, @endDateTime)
							end
							puts @bookableDates
							render "showDoctorForSecretary"
						end
				end

			when "Owner"
				case params[:type]
					when "Doctor"
						params.require(:clinic_id)
						params.require(:id)
						@doctor = User.get_doctors.find(params[:id])
						@clinic = Clinic.find(params[:clinic_id])
						@works = Work.where("clinic_id = ? AND doctor_id = ? ", params[:clinic_id], params[:id])
						@days = ["Domenica", "Lunedi", "Martedi", "Mercoledi", "Giovedi", "Venerdi", "Sabato"]
						render "ownerClinicDoctorsShow"
				end

			when "Patient"
				case params[:type]
					when "Doctor"
						# Patients want to see doctor and wants to book an examination
						# I need doctor id and clinic id
						if params[:date] == nil
							redirect_to clinic_doctor_path(params[:clinic_id], params[:id])+"?date="+DateTime.now.to_date.to_s
						else
							@clinic = Clinic.find(params[:clinic_id])
							@doctor = User.get_doctors.find(params[:id])
							@examinations = getExaminations()
							@nextDay = (params[:date].to_date + 1.days).to_s
							@previousDay = (params[:date].to_date - 1.days).to_s
							@works = Work.select('day, start_time, end_time').where("clinic_id = ? AND doctor_id = ? AND day = ?", params[:clinic_id], params[:id], params[:date].to_date.wday)
							@bookableDates = []
							if @works.length != 0
								@startDateTime = params[:date] + " " + @works[0].start_time
								@endDateTime = params[:date] + " " + @works[0].end_time
								@bookableDates = getBookableDates(@examinations, @startDateTime, @endDateTime)
							end
							#puts @bookableDates
							render "patientDoctorShow"
						end
					when "Secretary"

					when "Owner"

					when "Patient"
				end
		end
	end

	def create
		@user = User.new(user_params)
		@user.roles_mask = 0
		# We store all emails in lowercase to avoid duplicates and case-sensitive login errors
		#@user.email.downcase!

		if @user.save
			@user.send_activation_email
			flash[:info] = "Controlla la tua mail per attivare l'account"
			redirect_to root_path
		else
			flash.now.alert = "Impossibile creare l'account."
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def newOauth
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		if user.update(user_params)
			redirect_to "/home/show"
		else
			flash[:errors] = user.errors.full_messages
			render :edit
		end
	end



	def newOwner
		user = User.find(params[:id])
		#user.type = 'Owner'
		user.roles_mask = user.roles_mask | 1
		user.save!(validate: false)
		session[:type] = 'Owner'
	end

	def newDoctor
		user = User.find(params[:id])
		# Check if the user has set his doctorID
		if user.doctorID != nil
			# If it's set, redirect to the main page of doctor where he can choose its clinic
			session[:type] = 'Doctor'
			redirect_to doctor_path(user)
		else
			# The user must set the doctorID
			redirect_to set_doctorid_path(user)
		end
	end

	def checkDoctorID
		user = User.find(params[:id])
	end

	# Method to get information about user that wants to set a doctorID
	def setDoctorID
		@user = User.find(params[:id])
	end

	# Method to check if the doctorID is valid. If it's valid it will be written on DB
	def patchDoctorID
		user = User.find(params[:id])
		path = Rails.root + "matricole.csv"
		doctorID = params[:doctorID]
		# Open the file with the doctors' ids and check if the information are correct
		# The file has records like SURNAME;NAME;BIRTHDATE(GG/MM/AAAA);BIRTHCITY;DOCTORID\n
		if File.exist?(path)
			File.foreach(path, "\n") do |row|
				# Remove the line feed at the end of the row
				row = row.chomp
				# Splitting the row using delimeter ;
				doctor = row.split(";")
				#puts doctor
				if doctor[4] == doctorID && user.surname.downcase == doctor[0].downcase && user.name.downcase == doctor[1].downcase && user.birthdayDate == doctor[2] && user.birthdayPlace.downcase == doctor[3].downcase
					# Found the doctor in the file and the information are correct
					#user.type = "Doctor"
					user.doctorID = doctor[4]
					user.roles_mask = user.roles_mask | 8
					user.save!(validate: false)
					puts "Trovato!"
				else
					#puts user.surname.downcase == doctor[0].downcase
					#puts user.name.downcase == doctor[1].downcase
					#puts user.birthdayDate == doctor[2]
					#puts user.birthdayPlace.downcase == doctor[3].downcase
					puts "Non corrisponde"
				end
			end
		else
			puts "File non esistente"
		end
		redirect_to new_doctor_path(user)
	end



	def newPatient
		user = User.find(params[:id])
		#user.type = 'Patient'
		user.roles_mask = user.roles_mask | 4
		user.save!(validate: false)
		session[:type] = 'Patient'

	end

	def newSecretary
		user = User.find(params[:id])
		#user.type = 'Secretary'
		user.roles_mask = user.roles_mask | 2
		user.save!(validate: false)
		session[:type] = 'Secretary'
	end

	# Patient's functions

	def showPatientStory
		@patient = User.get_patients.find(params[:id])
		#puts @patient
	end

	def searchClinic
		@clinics = Clinic.all.order('created_at DESC')
		#puts session
		#puts session[:user_id]
		@clinics = @clinics.search(params[:search]) if params[:search].present?
	end

	def getExaminations
		# Get doctor's examinations date in a clinic and when the patients can get an examination
		# Date has format AAAA-MM-GG
		params.permit(:clinic_id, :id, :date)
		examinations = Examination.select("start_time").where("clinic_id = ? AND doctor_id = ? AND start_time >= ? AND start_time <= ?", params[:clinic_id], params[:id],params[:date]+" 00:00:00", params[:date]+" 23:59:59")
		examinations
	end

	# Get all the intervals of 30 minutes from startTime to endTime and the availability of that spot
	def getBookableDates(examinations, startTime, endTime)
		# Get all intervals of 30 minutes from start time to end time
		# Ex startTime = 9:00 endTime = 11:00 -> 9:00, 9:30, 10:00, 10:30, 11:00
		bookableDates = []
		time = startTime.to_datetime
		while time <= endTime
			bookable = checkDateAvailabilty(examinations, time)
			bookableDates.push([time, bookable])
			time = time + 30.minutes
		end

iMedical/app/helpers/users_helper.rb
module UsersHelper
end

iMedical/app/views/users/doctorPatients.html.erb
<h2> Lista pazienti di un dottore di una determinata clinica </h2>
<table border="1" style="width:50%">
	<% @patients.each do |patient| %>
		<tr> 
			<td> <%= patient.cf %> </td> 
			<td> <%= patient.surname + " " + patient.name %> </td>
			<td> <%= patient.birthdayDate %> </td>
			<td> <%= button_to "Visualizza paziente", clinic_patient_path(@clinic, patient), method: :get %> </td>
		</tr>
	<% end %>
</table>

iMedical/app/views/users/edit.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f| %>
			<%= render 'shared/error_messages' %>
			<div>
				<%= f.label :nome%>
				<%= f.text_field :name, autofocus: true, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :cognome%>
				<%= f.text_field :surname, autofocus: true, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :email%>
				<%= f.text_field :email, class: 'form-control'%>
			</div>

			<div>
				<%= f.label :password%>
				<%= f.password_field :password, class: 'form-control'%>
			</div>

			<div>
				<%= f.label :password_confirmation, "Conferma Password"%>
				<%= f.password_field :password_confirmation, class: 'form-control'%>
			</div>

			<div>
				<%= f.label :phoneNumber, "Numero di Telefono"%>
				<%= f.text_field :phoneNumber, class: 'form-control' %>
			</div>

			<div>
				<%= f.submit "Salva cambiamenti", class: "btn btn-primary" %>
			</div>

		<% end %>
	</div>
</div>

iMedical/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f| %>
			<%= render 'shared/error_messages' %>
			<div>
				<%= f.label :nome%>
				<%= f.text_field :name, autofocus: true, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :cognome%>
				<%= f.text_field :surname, autofocus: true, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :email%>
				<%= f.text_field :email, class: 'form-control'%>
			</div>

			<div>
				<%= f.label :password%>
				<%= f.password_field :password, class: 'form-control'%>
			</div>

			<div>
				<%= f.label :password_confirmation, "Conferma Password"%>
				<%= f.password_field :password_confirmation, class: 'form-control'%>
			</div>

			<div>
				<%= f.label :birthdayDate, "Data di nascita"%>
				<%= f.text_field :birthdayDate, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :birthdayPlace, "Luogo di Nascita"%>
				<%= f.text_field :birthdayPlace, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :phoneNumber, "Numero di Telefono"%>
				<%= f.text_field :phoneNumber, class: 'form-control' %>
			</div>

			<div>
				<%= f.label :cf, "Codice Fiscale"%>
				<%= f.text_field :cf, class: 'form-control' %>
			</div>

			<div>
				<%= f.submit "Sign up!", class: "btn btn-primary" %>
			</div>

		<% end %>
	</div>
</div>

iMedical/app/views/users/newDoctor.html.erb
<h2>DOTTORE</h2>

iMedical/app/views/users/newOauth.html.erb
<% provide(:title, 'Signup OAuth') %>
<h1>Completa Iscrizione</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f| %>
			<%= render 'shared/error_messages' %>
			<div>
				<%= f.label :name%>
				<%= f.text_field :name, autofocus: true %>
			</div>

			<div>
				<%= f.label :surname%>
				<%= f.text_field :surname, autofocus: true %>
			</div>

			<div>
				<%= f.label :email%>
				<%= f.text_field :email%>
			</div>

			<div>
				<%= f.label :birthdayDate%>
				<%= f.text_field :birthdayDate %>
			</div>

			<div>
				<%= f.label :birthdayPlace%>
				<%= f.text_field :birthdayPlace %>
			</div>

			<div>
				<%= f.label :phoneNumber%>
				<%= f.text_field :phoneNumber %>
			</div>

			<div>
				<%= f.label :cf%>
				<%= f.text_field :cf %>
			</div>

			<div>
				<%= f.submit "Completa!", class: "btn btn-primary"%>
			</div>
		<% end %>
	</div>
</div>

iMedical/app/views/users/newOwner.html.erb
<!DOCTYPE html>
<html>
  <head>
    <h1>HOME PAGE PROPRIETARIO</h1>
  </head>
  <body>
    <div>
        <h2>Signed in as <strong><%= current_user.email %></strong>!</h2>
        <h1>Operazioni</h1>
        <br/>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <%= button_to "Crea nuovo studio medico", new_owner_clinic_path(current_user.id), :method => "get", class: "btn"%>
                </div>
                <div class="col-sm-6 text-right">
                    <%= button_to "Gestisci studio medico", owner_clinics_path(current_user.id), :method => "get", class: "btn"%>
                </div>
            </div>
        </div>
        <br/>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <%= button_to "Aggiungi medico", show_clinicsDoctor_path(current_user.id), :method => "get", class: "btn"%>
                </div>
                <div class="col-sm-6 text-right">
                    <%= button_to "Aggiungi Segretario", show_clinicsSecretary_path(current_user.id), :method => "get", class: "btn"%>
                </div>
            </div>
        </div>
  </body>
</html>

iMedical/app/views/users/newPatient.html.erb
<!DOCTYPE html>
<html>
  <head>
    <h1>HOME PAGE PAZIENTE</h1>
  </head>
  <body>
    <div>
        <h2>Signed in as <strong><%= current_user.email %></strong>!</h2>
        <h1>Operazioni</h1>
        <br/>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <%#button_to "Visualizza cartella clinica", show_patient_story_path(current_user.id), :method => "get", class: "btn"%>
                </div>
                <div class="col-sm-6 text-right">
                    <%= button_to "Cerca studio medico", search_clinic_path, :method => "get", class: "btn"%>
                </div>
            </div>
        </div>
        <br/>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <%= button_to "Visualizza visite", patient_examinations_path(current_user.id), :method => "get", class: "btn"%>
                </div>
                <div class="col-sm-6 text-right">
                    <% #button_to "Visualizza prescrizioni", patient_prescriptions_path(current_user.id), class: "btn"%>
                </div>
            </div>
        </div>

  </body>
</html>

iMedical/app/views/users/newSecretary.html.erb
<h2>SEGRETARIO</h2>

<%= button_to "Seleziona studio medico", show_clinics_path(current_user.id), :method => "get", class: "btn"%>

iMedical/app/views/users/ownerClinicDoctorsShow.html.erb
<h2> Dottore che lavora in una certa clinica per un certo proprietario </h2>
Dottore: <%= @doctor.surname + " " + @doctor.name %> <br>
Clinica: <%= @clinic.name %> <br>
<br>
<table border="1">
	<%= @works.each do |work| %>
		<tr>
			<td> <%= work.id %> </td>
			<td> <%= @days[work.day] %> </td>
			<td> <%= work.start_time %> </td>
			<td> <%= work.end_time %> </td>
			<td> <%= button_to "Elimina giorno di lavoro", work_path(work), method: :delete %> </td>
		</tr>
	<% end %>
</table>
<br>
<%= link_to "Aggiungi giorno di lavoro", new_work_path(:clinic_id => @clinic.id, :doctor_id => @doctor.id) %>

iMedical/app/views/users/ownerClinicSecretariesIndex.html.erb
<h2> Lista segretari che lavorano in una determinata clinica di un certo proprietario (Vista proprietario)</h2>

<table border="1">
	<%= @secretaries.each do |secretary| %>
		<tr>
			<td> <%= secretary.surname + " " + secretary.name %> </td>
			<td> <%= button_to "Elimina segretario dalla clinica", manage_path(secretary.id), method: :delete %> </td>
		</tr>
	<% end %>
</table>

iMedical/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <h1>COMPLETA ISCRIZIONE</h1>
  </head>
  <body>
    <div>
        Signed in as <strong><%= current_user.email %></strong>!
        <br/>
        <%= link_to "Completa iscrizione", newOauth_path(current_user.id), id: "sigOauth" %>
      </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

iMedical/app/views/users/showDoctor.html.erb
<h2> Lista cliniche </h2><br>

<br>
<table border="1">
	<% @clinics.each do |clinic| %>
		<tr>
			<td> <%= clinic.name %> </td>
			<td> <%= button_to "Visualizza clinica", clinic_path(clinic), method: :get %> </td>
		</tr>
	<% end %>
</table>

iMedical/app/views/users/showDoctorForSecretary.html.erb
<h2> Appuntamenti Segretario </h2>

<br> <%#link_to "Visualizza prescrizioni", clinic_doctor_examinations_path(params[:clinic_id], params[:id])  %>
 </br>

Dottore: <%= @doctor.surname %> <%= @doctor.name %> <br>

<h2> Prenota </h2>
<div id="calendario">
	<div>
		<%= button_to "Previous day", clinic_doctor_path(@clinic, @doctor), method: :get, params: {date: @previousDay} %>
		<input type="date" id="dataAttuale" value=<%= params[:date] %>>
		<%= button_to "Next day", clinic_doctor_path(@clinic, @doctor), method: :get, params: {date: @nextDay} %>
	</div>
	<div id ="date">
		<% if @bookableDates.length > 0 %>
			<%= @bookableDates.each do |date| %>
				<div>
					<%= date[0].to_formatted_s(:db) %> 
					<% if date[1] %>
						<%= button_to "Prenota Paziente", search_patient_path(session[:user_id], params[:clinic_id], params[:id]), params: { date: date[0].to_formatted_s(:db)}, :method => :get %>
					<% else %>
						<% if Examination.where("clinic_id = ? AND doctor_id = ? AND start_time = ?", params[:clinic_id], params[:id], date[0].to_formatted_s(:db).to_datetime).length > 0 %>
							<% if Time.now >= date[0].to_formatted_s(:db).to_datetime %>
								<%= button_to "Visita già effettuata", examination_path(Examination.where("clinic_id = ? AND doctor_id = ? AND start_time = ?", params[:clinic_id], params[:id], date[0].to_formatted_s(:db).to_datetime)[0].id) , :method => :delete, :disabled => true %>
							<% else %>
								<%= button_to "Annulla Visita", examination_path(Examination.where("clinic_id = ? AND doctor_id = ? AND start_time = ?", params[:clinic_id], params[:id], date[0].to_formatted_s(:db).to_datetime)[0].id) , :method => :delete %>
							<% end %>
							<%= User.get_patients.find(Examination.where("clinic_id = ? AND doctor_id = ? AND start_time = ?", params[:clinic_id], params[:id], date[0].to_formatted_s(:db).to_datetime)[0].patient_id).surname %> 
							<%= User.get_patients.find(Examination.where("clinic_id = ? AND doctor_id = ? AND start_time = ?", params[:clinic_id], params[:id], date[0].to_formatted_s(:db).to_datetime)[0].patient_id).name %>
						<% else %>
							<%= "Non prenotabile" %>
						<% end %>
					<% end %>
				</div>
			<% end %>
		<% else %>
			<%= "Il medico non riceve in questo giorno della settimana" %>
		<% end %>
	</div>
</div>

iMedical/app/views/users/showPatientStory.html.erb
<h1>CARTELLA CLINICA</h1>

<h2>
    <% if @patient.story.blank? %>
        La cartella clinica è vuota
    <% else %>
        <%= @patient.story %>
    <% end %>
</h2>